"""
Automated email alert system for sales anomalies and KPI threshold breaches.
Triggered by Databricks Jobs scheduler after each pipeline run.
"""

from __future__ import annotations

import os
import smtplib
import ssl
from dataclasses import dataclass
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from string import Template
from typing import Any

import pandas as pd


@dataclass
class AlertConfig:
    smtp_host: str = "smtp.gmail.com"
    smtp_port: int = 465
    sender_email: str = ""
    sender_password: str = ""  # Use Databricks secrets in production
    recipients: list[str] = None

    def __post_init__(self):
        self.sender_email   = os.getenv("ALERT_EMAIL",    self.sender_email)
        self.sender_password = os.getenv("ALERT_PASSWORD", self.sender_password)
        if self.recipients is None:
            self.recipients = os.getenv("ALERT_RECIPIENTS", "").split(",")


_ANOMALY_TEMPLATE = Template("""
<html><body>
<h2 style="color:#c0392b;">⚠ Sales Anomaly Detected — $run_date</h2>
<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;font-family:Arial">
  <tr style="background:#2c3e50;color:white">
    <th>Region</th><th>Date</th><th>Daily Revenue</th><th>Rolling Mean</th><th>Z-Score</th>
  </tr>
  $rows
</table>
<br/>
<p><b>Revenue at risk: $$revenue_at_risk</b></p>
<p style="color:grey;font-size:11px">Auto-generated by Sales Analytics Pipeline · $run_date</p>
</body></html>
""")

_KPI_TEMPLATE = Template("""
<html><body>
<h2 style="color:#e67e22;">📊 KPI Threshold Alert — $run_date</h2>
<ul>$kpi_items</ul>
<p style="color:grey;font-size:11px">Auto-generated by Sales Analytics Pipeline · $run_date</p>
</body></html>
""")


class SalesAlertSender:
    def __init__(self, config: AlertConfig | None = None):
        self.config = config or AlertConfig()

    def send_anomaly_alert(self, anomalies: pd.DataFrame) -> None:
        if anomalies.empty:
            return

        rows_html = "".join(
            f"<tr><td>{r.region}</td><td>{r.sale_date}</td>"
            f"<td>${r.daily_revenue:,.0f}</td><td>${r.rolling_mean:,.0f}</td>"
            f"<td>{r.z_score:.2f}</td></tr>"
            for r in anomalies.itertuples()
        )
        revenue_at_risk = f"{anomalies['daily_revenue'].sum():,.0f}"
        html = _ANOMALY_TEMPLATE.substitute(
            run_date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            rows=rows_html,
            revenue_at_risk=revenue_at_risk,
        )
        self._send(
            subject=f"[ALERT] {len(anomalies)} Sales Anomalies Detected",
            html_body=html,
        )

    def send_kpi_alert(self, breaches: list[dict[str, Any]]) -> None:
        if not breaches:
            return

        items_html = "".join(
            f"<li><b>{b['kpi']}</b>: actual={b['actual']:,.1f} "
            f"vs threshold={b['threshold']:,.1f} ({b['direction']})</li>"
            for b in breaches
        )
        html = _KPI_TEMPLATE.substitute(
            run_date=datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            kpi_items=items_html,
        )
        self._send(
            subject=f"[KPI ALERT] {len(breaches)} threshold(s) breached",
            html_body=html,
        )

    # ------------------------------------------------------------------

    def _send(self, subject: str, html_body: str) -> None:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"]    = self.config.sender_email
        msg["To"]      = ", ".join(self.config.recipients)
        msg.attach(MIMEText(html_body, "html"))

        ctx = ssl.create_default_context()
        with smtplib.SMTP_SSL(self.config.smtp_host, self.config.smtp_port, context=ctx) as server:
            server.login(self.config.sender_email, self.config.sender_password)
            server.sendmail(
                self.config.sender_email,
                self.config.recipients,
                msg.as_string(),
            )
        print(f"Alert sent: {subject}")


# ------------------------------------------------------------------
# Databricks Job entry-point
# ------------------------------------------------------------------

def run_on_databricks():
    from pyspark.sql import SparkSession  # noqa: PLC0415

    spark   = SparkSession.builder.getOrCreate()
    sender  = SalesAlertSender()

    # Anomaly alerts
    anomalies = spark.table("gold.revenue_anomalies_ml").toPandas()
    sender.send_anomaly_alert(anomalies)

    # KPI threshold alerts
    kpis = spark.sql("""
        SELECT
            SUM(net_revenue)   AS monthly_revenue,
            AVG(discount_pct)  AS avg_discount
        FROM silver.silver_sales_transactions
        WHERE order_year = YEAR(CURRENT_DATE())
          AND order_month = MONTH(CURRENT_DATE())
    """).collect()[0]

    breaches = []
    if kpis["monthly_revenue"] < 500_000:
        breaches.append({
            "kpi":       "Monthly Net Revenue",
            "actual":    kpis["monthly_revenue"],
            "threshold": 500_000,
            "direction": "below target",
        })
    if kpis["avg_discount"] > 0.20:
        breaches.append({
            "kpi":       "Avg Discount %",
            "actual":    kpis["avg_discount"] * 100,
            "threshold": 20,
            "direction": "above limit",
        })

    sender.send_kpi_alert(breaches)


if __name__ == "__main__":
    run_on_databricks()
